# Generated by Django 3.0.3 on 2020-04-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DeCaffeineShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decaffeine_espresso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'decaffeine_shots',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=200)),
                ('is_mydrink', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Category')),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sat_fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('ml', models.IntegerField()),
                ('oz', models.IntegerField()),
                ('nutrition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Nutrition')),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Drink')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='DrinkAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Allergy')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Drink')),
            ],
            options={
                'db_table': 'drinks_allergies',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='nutrition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Nutrition'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_top', models.CharField(max_length=1000)),
                ('description_bottom', models.CharField(max_length=1000)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Drink')),
            ],
            options={
                'db_table': 'descriptions',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='decaffeine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.DeCaffeineShot'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.MainMenu'),
        ),
    ]
