# Generated by Django 3.0.3 on 2020-04-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='description',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='nutrition_id',
        ),
        migrations.RemoveField(
            model_name='drinkimage',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='size',
            name='nutrition_id',
        ),
        migrations.AddField(
            model_name='description',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Drink'),
        ),
        migrations.AddField(
            model_name='drink',
            name='allergy_drink',
            field=models.ManyToManyField(through='drink.DrinkAllergy', to='drink.Allergy'),
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Category'),
        ),
        migrations.AddField(
            model_name='drink',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.MainMenu'),
        ),
        migrations.AddField(
            model_name='drink',
            name='nutrition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Nutrition'),
        ),
        migrations.AddField(
            model_name='drinkimage',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Drink'),
        ),
        migrations.AddField(
            model_name='size',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Nutrition'),
        ),
        migrations.AlterField(
            model_name='category',
            name='decaffeine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.DeCaffeineShot'),
        ),
        migrations.AlterField(
            model_name='drinkallergy',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Allergy'),
        ),
        migrations.AlterField(
            model_name='drinkallergy',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink.Drink'),
        ),
        migrations.AlterField(
            model_name='drinkimage',
            name='image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='size',
            name='ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='oz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='mainmenu',
            table='menu',
        ),
    ]
